// ignore_for_file: unnecessary_string_escapes

import 'package:get/get.dart';

final class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // ENGLISH LANGUAGE
        "en_US": {
          // Common & Auth
          "skip": "SKIP",
          "getStarted": "Get Started",
          "Next": "Next",
          "Welcome back!": "Welcome back!",
          "Welcome Back": "Welcome Back",
          "signInAndStartExploring": "Sign in and start exploring",
          "Sign in to continue": "Sign in to continue",
          "Sign In": "Sign In",
          "Login": "Login",
          "Or sign in with": "Or sign in with",
          "Sign in with Google": "Sign in with Google",
          "dontHaveAnAccount": "Don't have an account? ",
          "signUp": "Sign Up",
          "Enter 4-digit verification code": "Enter 4-digit verification code",
          "Your code was sent to +(1) xxxx-xxxx": "Your code was sent to +(1) xxxx-xxxx",
          "Didn't receive code?": "Didn't receive code?",
          "Resend": "Resend",
          "Confirm": "Confirm",
          "Your phone number was verified successfully": "Your phone number was verified successfully",
          "Welcome to VIBE": "Welcome to VIBE",
          "Create an account to get started your journey.": "Create an account to get started your journey.",
          "Create Account": "Create Account",
          "Fill in your details to get started": "Fill in your details to get started",
          "Sign Up": "Sign Up",
          "Full Name": "Full Name",
          "Father's Name": "Father's Name",
          "Email Address": "Email Address",
          "Password": "Password",
          "Male": "Male",
          "Female": "Female",
          "Other": "Other",
          "Birth date": "Birth date",
          "Phone Number": "Phone Number",
          "NID Number": "NID Number",
          "Continue": "Continue",
          "Or sign up with": "Or sign up with",
          "Sign Up with Google": "Sign Up with Google",
          "Have An Account": "Have An Account",
          "Already have an account?": "Already have an account? ",
          "Done": "Done",
          "Cancel": "Cancel",
          "Select your birth date": "Select your birth date",
          "Year-Month-Day": "Year-Month-Day",
          "Invalid date format": "Invalid date format",
          "Invalid date": "Invalid date",
          "Select Language": "Select Language",
          "English": "English",
          "Bangla": "Bangla",
          "Agree with all": "Agree with all ",
          "Terms and Conditions & Privacy Policy": "Terms and Conditions & Privacy Policy",

          // Dashboard & Navigation
          "Home": "Home",
          "Scan": "Scan",
          "Products": "Products",
          "Orders": "Orders",
          "Profile": "Profile",
          "Dashboard": "Dashboard",
          "Welcome": "Welcome",
          "Farmer": "Farmer",
          "Services": "Services",
          "History": "History",
          "Settings": "Settings",
          "Logout": "Logout",

          // Crop Scanning
          "Crop Scan": "Crop Scan",
          "Scan Crop Leaf": "Scan Crop Leaf",
          "Detect Disease": "Detect Disease",
          "Take Photo": "Take Photo",
          "Choose from Gallery": "Choose from Gallery",
          "Scanning...": "Scanning...",
          "Analyzing Image": "Analyzing Image",
          "Scan Result": "Scan Result",
          "Disease Detected": "Disease Detected",
          "Healthy Plant": "Healthy Plant",
          "Detection Confidence": "Detection Confidence",
          "Scan Again": "Scan Again",
          "Save Result": "Save Result",
          "Camera Permission": "Camera Permission",
          "Gallery Permission": "Gallery Permission",
          "Please allow camera access to scan leaves": "Please allow camera access to scan leaves",
          "Please allow gallery access to select images": "Please allow gallery access to select images",

          // Problem Input
          "Describe Problem": "Describe Problem",
          "Crop Type": "Crop Type",
          "Problem Description": "Problem Description",
          "Select Crop": "Select Crop",
          "Rice": "Rice",
          "Wheat": "Wheat",
          "Corn": "Corn",
          "Potato": "Potato",
          "Tomato": "Tomato",
          "Other Crops": "Other Crops",
          "Symptoms": "Symptoms",
          "When did you notice the problem?": "When did you notice the problem?",
          "Affected Area": "Affected Area",
          "Submit Problem": "Submit Problem",
          "Problem Submitted": "Problem Submitted",

          // Pesticide Suggestions
          "Recommended Pesticides": "Recommended Pesticides",
          "Suggested Solutions": "Suggested Solutions",
          "Pesticide Name": "Pesticide Name",
          "Dosage": "Dosage",
          "Application Method": "Application Method",
          "Safety Instructions": "Safety Instructions",
          "Effectiveness": "Effectiveness",
          "Price": "Price",
          "Alternative Solutions": "Alternative Solutions",
          "Organic Options": "Organic Options",
          "Chemical Options": "Chemical Options",
          "Prevention Tips": "Prevention Tips",

          // Products & Marketplace
          "Marketplace": "Marketplace",
          "Pesticides": "Pesticides",
          "Fertilizers": "Fertilizers",
          "Seeds": "Seeds",
          "Tools": "Tools",
          "All Products": "All Products",
          "Featured Products": "Featured Products",
          "Best Sellers": "Best Sellers",
          "New Arrivals": "New Arrivals",
          "Product Details": "Product Details",
          "Add to Cart": "Add to Cart",
          "Buy Now": "Buy Now",
          "Out of Stock": "Out of Stock",
          "In Stock": "In Stock",
          "Quantity": "Quantity",
          "Reviews": "Reviews",
          "Similar Products": "Similar Products",
          "Search Products": "Search Products",

          // Cart & Orders
          "Shopping Cart": "Shopping Cart",
          "Your Cart": "Your Cart",
          "Cart is Empty": "Cart is Empty",
          "Total Items": "Total Items",
          "Subtotal": "Subtotal",
          "Delivery Charge": "Delivery Charge",
          "Total Amount": "Total Amount",
          "Proceed to Checkout": "Proceed to Checkout",
          "Checkout": "Checkout",
          "Shipping Address": "Shipping Address",
          "Payment Method": "Payment Method",
          "Order Summary": "Order Summary",
          "Place Order": "Place Order",
          "Order Placed": "Order Placed",
          "Order Confirmed": "Order Confirmed",
          "Order History": "Order History",
          "Order Details": "Order Details",
          "Track Order": "Track Order",
          "Order Status": "Order Status",
          "Pending": "Pending",
          "Confirmed": "Confirmed",
          "Shipped": "Shipped",
          "Delivered": "Delivered",
          "Cancelled": "Cancelled",

          // Seller Features
          "Become a Seller": "Become a Seller",
          "Seller Dashboard": "Seller Dashboard",
          "My Products": "My Products",
          "Add Product": "Add Product",
          "Edit Product": "Edit Product",
          "Sales Analytics": "Sales Analytics",
          "Seller Application": "Seller Application",
          "Apply as Seller": "Apply as Seller",
          "Seller Terms": "Seller Terms",
          "Upload Documents": "Upload Documents",
          "Store Name": "Store Name",
          "Business License": "Business License",
          "Tax ID": "Tax ID",
          "Bank Details": "Bank Details",
          "Seller Approval Pending": "Seller Approval Pending",
          "Seller Approved": "Seller Approved",

          // Notifications & Alerts
          "Notifications": "Notifications",
          "Alerts": "Alerts",
          "New Message": "New Message",
          "Order Update": "Order Update",
          "Price Drop": "Price Drop",
          "New Recommendation": "New Recommendation",
          "Weather Alert": "Weather Alert",
          "Crop Alert": "Crop Alert",

          // Weather & Farming Tips
          "Weather Forecast": "Weather Forecast",
          "Farming Tips": "Farming Tips",
          "Today's Weather": "Today's Weather",
          "Weekly Forecast": "Weekly Forecast",
          "Soil Health": "Soil Health",
          "Irrigation Tips": "Irrigation Tips",
          "Harvesting Guide": "Harvesting Guide",

          // Support & Help
          "Help & Support": "Help & Support",
          "Contact Us": "Contact Us",
          "Customer Service": "Customer Service",
          "Report Problem": "Report Problem",
          "Feedback": "Feedback",
          "Rate App": "Rate App",
          "About Us": "About Us",
          "Privacy Policy": "Privacy Policy",
          "Terms of Service": "Terms of Service",
        },

        // BANGLA LANGUAGE
        "bn_BD": {
          // Common & Auth
          "skip": "এড়িয়ে যান",
          "getStarted": "শুরু করুন",
          "Next": "পরবর্তী",
          "Welcome back!": "আবার স্বাগতম!",
          "Welcome Back": "আবার স্বাগতম",
          "signInAndStartExploring": "সাইন ইন করুন এবং অন্বেষণ শুরু করুন",
          "Sign in to continue": "চালিয়ে যেতে সাইন ইন করুন",
          "Sign In": "সাইন ইন",
          "Login": "লগইন",
          "Or sign in with": "বা দিয়ে সাইন ইন করুন",
          "Sign in with Google": "Google দিয়ে সাইন ইন করুন",
          "dontHaveAnAccount": "অ্যাকাউন্ট নেই? ",
          "signUp": "সাইন আপ করুন",
          "Enter 4-digit verification code": "৪-সংখ্যার যাচাই কোড লিখুন",
          "Your code was sent to +(1) xxxx-xxxx": "আপনার কোড +(১) xxxx-xxxx এ পাঠানো হয়েছে",
          "Didn't receive code?": "কোড পাননি?",
          "Resend": "পুনরায় পাঠান",
          "Confirm": "নিশ্চিত করুন",
          "Your phone number was verified successfully": "আপনার ফোন নম্বর সফলভাবে যাচাই করা হয়েছে",
          "Welcome to VIBE": "VIBE-এ স্বাগতম",
          "Create an account to get started your journey.": "আপনার যাত্রা শুরু করতে একটি অ্যাকাউন্ট তৈরি করুন।",
          "Create Account": "অ্যাকাউন্ট তৈরি করুন",
          "Fill in your details to get started": "শুরু করতে আপনার বিবরণ পূরণ করুন",
          "Sign Up": "সাইন আপ করুন",
          "Full Name": "পূর্ণ নাম",
          "Father's Name": "পিতার নাম",
          "Email Address": "ইমেল ঠিকানা",
          "Password": "পাসওয়ার্ড",
          "Male": "পুরুষ",
          "Female": "মহিলা",
          "Other": "অন্যান্য",
          "Birth date": "জন্ম তারিখ",
          "Phone Number": "ফোন নম্বর",
          "NID Number": "এনআইডি নম্বর",
          "Continue": "চালিয়ে যান",
          "Or sign up with": "বা দিয়ে সাইন আপ করুন",
          "Sign Up with Google": "Google দিয়ে সাইন আপ করুন",
          "Have An Account": "অ্যাকাউন্ট আছে",
          "Already have an account?": "ইতিমধ্যে একটি অ্যাকাউন্ট আছে? ",
          "Done": "সম্পন্ন",
          "Cancel": "বাতিল",
          "Select your birth date": "আপনার জন্ম তারিখ নির্বাচন করুন",
          "Year-Month-Day": "বছর-মাস-দিন",
          "Invalid date format": "অবৈধ তারিখ ফর্ম্যাট",
          "Invalid date": "অবৈধ তারিখ",
          "Select Language": "ভাষা নির্বাচন করুন",
          "English": "ইংরেজি",
          "Bangla": "বাংলা",
          "Agree with all": "সকলের সাথে সম্মত",
          "Terms and Conditions & Privacy Policy": "শর্তাবলী এবং গোপনীয়তা নীতি",

          // Dashboard & Navigation
          "Home": "হোম",
          "Scan": "স্ক্যান",
          "Products": "পণ্য",
          "Orders": "অর্ডার",
          "Profile": "প্রোফাইল",
          "Dashboard": "ড্যাশবোর্ড",
          "Welcome": "স্বাগতম",
          "Farmer": "কৃষক",
          "Services": "সেবা",
          "History": "ইতিহাস",
          "Settings": "সেটিংস",
          "Logout": "লগআউট",

          // Crop Scanning
          "Crop Scan": "ফসল স্ক্যান",
          "Scan Crop Leaf": "ফসলের পাতা স্ক্যান করুন",
          "Detect Disease": "রোগ সনাক্ত করুন",
          "Take Photo": "ছবি তুলুন",
          "Choose from Gallery": "গ্যালারি থেকে নির্বাচন করুন",
          "Scanning...": "স্ক্যান করা হচ্ছে...",
          "Analyzing Image": "ছবি বিশ্লেষণ করা হচ্ছে",
          "Scan Result": "স্ক্যান ফলাফল",
          "Disease Detected": "রোগ সনাক্ত হয়েছে",
          "Healthy Plant": "সুস্থ গাছ",
          "Detection Confidence": "সনাক্তকরণ আত্মবিশ্বাস",
          "Scan Again": "আবার স্ক্যান করুন",
          "Save Result": "ফলাফল সংরক্ষণ করুন",
          "Camera Permission": "ক্যামেরা অনুমতি",
          "Gallery Permission": "গ্যালারি অনুমতি",
          "Please allow camera access to scan leaves": "পাতা স্ক্যান করতে ক্যামেরা অ্যাক্সেস অনুমতি দিন",
          "Please allow gallery access to select images": "ছবি নির্বাচন করতে গ্যালারি অ্যাক্সেস অনুমতি দিন",

          // Problem Input
          "Describe Problem": "সমস্যা বর্ণনা করুন",
          "Crop Type": "ফসলের ধরন",
          "Problem Description": "সমস্যার বর্ণনা",
          "Select Crop": "ফসল নির্বাচন করুন",
          "Rice": "ধান",
          "Wheat": "গম",
          "Corn": "ভুট্টা",
          "Potato": "আলু",
          "Tomato": "টমেটো",
          "Other Crops": "অন্যান্য ফসল",
          "Symptoms": "লক্ষণ",
          "When did you notice the problem?": "আপনি কখন সমস্যাটি লক্ষ্য করেছেন?",
          "Affected Area": "আক্রান্ত এলাকা",
          "Submit Problem": "সমস্যা জমা দিন",
          "Problem Submitted": "সমস্যা জমা দেওয়া হয়েছে",

          // Pesticide Suggestions
          "Recommended Pesticides": "প্রস্তাবিত কীটনাশক",
          "Suggested Solutions": "প্রস্তাবিত সমাধান",
          "Pesticide Name": "কীটনাশকের নাম",
          "Dosage": "মাত্রা",
          "Application Method": "প্রয়োগ পদ্ধতি",
          "Safety Instructions": "নিরাপত্তা নির্দেশিকা",
          "Effectiveness": "কার্যকারিতা",
          "Price": "দাম",
          "Alternative Solutions": "বিকল্প সমাধান",
          "Organic Options": "জৈব বিকল্প",
          "Chemical Options": "রাসায়নিক বিকল্প",
          "Prevention Tips": "প্রতিরোধ টিপস",

          // Products & Marketplace
          "Marketplace": "মার্কেটপ্লেস",
          "Pesticides": "কীটনাশক",
          "Fertilizers": "সার",
          "Seeds": "বীজ",
          "Tools": "যন্ত্রপাতি",
          "All Products": "সমস্ত পণ্য",
          "Featured Products": "বিশেষ পণ্য",
          "Best Sellers": "সেরা বিক্রেতা",
          "New Arrivals": "নতুন আগমন",
          "Product Details": "পণ্যের বিবরণ",
          "Add to Cart": "কার্টে যোগ করুন",
          "Buy Now": "এখন কিনুন",
          "Out of Stock": "স্টক নেই",
          "In Stock": "স্টকে আছে",
          "Quantity": "পরিমাণ",
          "Reviews": "রিভিউ",
          "Similar Products": "অনুরূপ পণ্য",
          "Search Products": "পণ্য অনুসন্ধান",

          // Cart & Orders
          "Shopping Cart": "শপিং কার্ট",
          "Your Cart": "আপনার কার্ট",
          "Cart is Empty": "কার্ট খালি",
          "Total Items": "মোট আইটেম",
          "Subtotal": "উপমোট",
          "Delivery Charge": "ডেলিভারি চার্জ",
          "Total Amount": "মোট Amount",
          "Proceed to Checkout": "চেকআউট继续进行",
          "Checkout": "চেকআউট",
          "Shipping Address": "শিপিং ঠিকানা",
          "Payment Method": "পেমেন্ট পদ্ধতি",
          "Order Summary": "অর্ডার সারাংশ",
          "Place Order": "অর্ডার দিন",
          "Order Placed": "অর্ডার দেওয়া হয়েছে",
          "Order Confirmed": "অর্ডার নিশ্চিত হয়েছে",
          "Order History": "অর্ডার ইতিহাস",
          "Order Details": "অর্ডার বিবরণ",
          "Track Order": "অর্ডার ট্র্যাক করুন",
          "Order Status": "অর্ডার স্ট্যাটাস",
          "Pending": "বিচারাধীন",
          "Confirmed": "নিশ্চিত",
          "Shipped": "শিপ করা হয়েছে",
          "Delivered": "ডেলিভারি হয়েছে",
          "Cancelled": "বাতিল",

          // Seller Features
          "Become a Seller": "বিক্রেতা হন",
          "Seller Dashboard": "বিক্রেতা ড্যাশবোর্ড",
          "My Products": "আমার পণ্য",
          "Add Product": "পণ্য যোগ করুন",
          "Edit Product": "পণ্য সম্পাদনা করুন",
          "Sales Analytics": "বিক্রয় বিশ্লেষণ",
          "Seller Application": "বিক্রেতা আবেদন",
          "Apply as Seller": "বিক্রেতা হিসাবে আবেদন করুন",
          "Seller Terms": "বিক্রেতা শর্তাবলী",
          "Upload Documents": "নথি আপলোড করুন",
          "Store Name": "দোকানের নাম",
          "Business License": "ব্যবসায়িক লাইসেন্স",
          "Tax ID": "ট্যাক্স আইডি",
          "Bank Details": "ব্যাংক বিবরণ",
          "Seller Approval Pending": "বিক্রেতা অনুমোদন মুলতুবি",
          "Seller Approved": "বিক্রেতা অনুমোদিত",

          // Notifications & Alerts
          "Notifications": "নোটিফিকেশন",
          "Alerts": "সতর্কতা",
          "New Message": "নতুন বার্তা",
          "Order Update": "অর্ডার আপডেট",
          "Price Drop": "দাম কমেছে",
          "New Recommendation": "নতুন সুপারিশ",
          "Weather Alert": "আবহাওয়া সতর্কতা",
          "Crop Alert": "ফসল সতর্কতা",

          // Weather & Farming Tips
          "Weather Forecast": "আবহাওয়ার পূর্বাভাস",
          "Farming Tips": "চাষাবাদের টিপস",
          "Today's Weather": "আজকের আবহাওয়া",
          "Weekly Forecast": "সাপ্তাহিক পূর্বাভাস",
          "Soil Health": "মাটির স্বাস্থ্য",
          "Irrigation Tips": "সেচ টিপস",
          "Harvesting Guide": "ফসল কাটার গাইড",

          // Support & Help
          "Help & Support": "সাহায্য ও সমর্থন",
          "Contact Us": "যোগাযোগ করুন",
          "Customer Service": "গ্রাহক সেবা",
          "Report Problem": "সমস্যা রিপোর্ট করুন",
          "Feedback": "ফিডব্যাক",
          "Rate App": "অ্যাপ রেট করুন",
          "About Us": "আমাদের সম্পর্কে",
          "Privacy Policy": "গোপনীয়তা নীতি",
          "Terms of Service": "সেবার শর্তাবলী",
        },
      };
}